sudo: required
services:
  - docker
install:
  - pip install awscli
before_script:
#  - ./budget_proj/bin/getconfig.sh
#  - source ./budget_proj/bin/env.sh
  - source ./budget_proj/bin/getconfig.sh
script:
  - ./budget_proj/bin/test-proj.sh
after_success:
  - ./budget_proj/bin/docker-push.sh
