budget-service:
  environment:
  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - CONFIG_BUCKET=${CONFIG_BUCKET}  
  - DEPLOY_TARGET=${DEPLOY_TARGET}
  - PROJ_SETTINGS_DIR=${PROJ_SETTINGS_DIR}
  build: .

# docker-compose complains if I enable the image key at the same time as the build key
# "ERROR: The Compose file is invalid because:
# "Service budget-service has both an image and build path specified. A service can either be built to image or use an existing image, not both."

#  image: "${DOCKER_REPO}/${DEPLOY_TARGET}/${DOCKER_IMAGE}:latest" 
  volumes:
    - .:/code
  ports:
    - "8000:8000"
